DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS district CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS orderLine CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS stock CASCADE;