DROP TABLE "Warehouse" CASCADE;
DROP TABLE "District" CASCADE;
DROP TABLE "Customer" CASCADE;
DROP TABLE "Order" CASCADE;
DROP TABLE "OrderLine" CASCADE;
DROP TABLE "Item" CASCADE;
DROP TABLE "Stock" CASCADE;